# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1227fef83a86f9dae97a3537bc5416d4aa3d24e97bafdc1135ca6453b049d5ca689e82e4420b0cd2c32e2b6195a8918c6d177ec12fb07d2ab3361460c9dd435

test:
  secret_key_base: 422614d58d86ce7d761eb721c29b3d341df7564ccc2d99486cd5ddec38d4cd4235faf98b0be48aa9156f68948237feb9326ba24f6520bce7633ac9e99e810939

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
